repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: mixed-line-ending
# Format
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
# Sort import
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
        - --profile
        - black
        name: isort (python)
# Modern python
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.6.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
# Testing Code
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast  # Is it valid Python?
    -   id: debug-statements
# Security
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: detect-aws-credentials
    -   id: detect-private-key
# Large file
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files