version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_DATABASE: django
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/vagrant
    ports:
      - 8000:8000
    depends_on:
      - db
      - memcached
      - redis
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint:
      - memcached
      - -m 64
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
volumes:
  redisdata:
  mysql:
    driver: local
