version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      MYSQL_DATABASE: django
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: .
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/vagrant
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  mysql:
    driver: local