# Generated by Django 3.1.3 on 2022-05-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avater',
            new_name='avatar',
        ),
    ]
