name: Twitter Project CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install Dependencies
        run: |
          sudo apt-get install -y mysql-server gcc libmariadb-dev
          pip install docker-compose
      - name: Run Tests
        run: |
          docker-compose run web sh -c "python manage.py wait_for_db && python manage.py test"
